In [27]:
import sys
sys.path.insert(0,"../../../")

import joblib
import pandas as pd
import json
from typing import List, Dict, Tuple, Set
from copy import deepcopy
import ast

from src.utils.data_structs import NodeType, RelationType, Triplet
from collections import defaultdict

In [65]:
BASE_DIR = "../../.." # TO CHANGE
SELECTED_BENCHMARK_NAME = "2wiki" # TO CHANGE
SELECTED_KNOWLEDGEGRAPH_NAME = "qwen257b_080226_v2prompts" # TO CHANGE

QA_DATASETS_DIR = f"{BASE_DIR}/data/qa_datasets"
KNOWLEDGE_GRAPHS_DIR = f"{BASE_DIR}/../pai2_knowledge_graphs"
EXTRACTED_TRIPLES_FILENAME = 'extracted_triplets'
TRIPLES_NODES_IDS_FILENAME = 'partial_triples_nodes_ids.joblib'
MATCHED_TNIDS_TO_QUESTIONS_FILENAME = 'matched_tnids_to_questions.joblib'

BENCHMARK_PATH = {
    'nq': {
        'qa': f"{QA_DATASETS_DIR}/natural_questions_train/qa_pairs.csv",
        'documents': f"{QA_DATASETS_DIR}/natural_questions_train/relevant_contexts.csv"
    }, 
    'triviaqa': {
        'qa': f"{QA_DATASETS_DIR}/v2/trivia_qa_rcwikipedia_validation/qa_pairs.csv",
        'documents': f"{QA_DATASETS_DIR}/v2/trivia_qa_rcwikipedia_validation/relevant_contexts.csv"
    }, 
    'hotpotqa': {
        'qa': f"{QA_DATASETS_DIR}/v2/hotpotqa_distractor_validation/qa_pairs.csv",
        'documents': f"{QA_DATASETS_DIR}/v2/hotpotqa_distractor_validation/relevant_contexts.csv"
    }, 
    '2wiki': {
        'qa': f"{QA_DATASETS_DIR}/2wikimultihopqa_dev/qa_pairs.csv",
        'documents': f"{QA_DATASETS_DIR}/2wikimultihopqa_dev/relevant_contexts.csv"
    }, 
    'musique': {
        'qa': f"{QA_DATASETS_DIR}/musique_validation/qa_pairs.csv",
        'documents': f"{QA_DATASETS_DIR}/musique_validation/relevant_contexts.csv"
    }
}

EXTRACTED_TRIPLES_PATH = f"{KNOWLEDGE_GRAPHS_DIR}/{SELECTED_BENCHMARK_NAME}/{SELECTED_KNOWLEDGEGRAPH_NAME}/{EXTRACTED_TRIPLES_FILENAME}"
SAVE_TRIPLES_NODES_IDS_PATH = f"{KNOWLEDGE_GRAPHS_DIR}/{SELECTED_BENCHMARK_NAME}/{SELECTED_KNOWLEDGEGRAPH_NAME}/{TRIPLES_NODES_IDS_FILENAME}"
SAVE_MATCHED_TNIDS_TO_QUESTIONS_PATH = f"{KNOWLEDGE_GRAPHS_DIR}/{SELECTED_BENCHMARK_NAME}/{SELECTED_KNOWLEDGEGRAPH_NAME}/{MATCHED_TNIDS_TO_QUESTIONS_FILENAME}"

In [10]:
EXTRACTED_TRIPLES = joblib.load(EXTRACTED_TRIPLES_PATH)

/home/dzigen/miniconda3/envs/pai/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
print(len(EXTRACTED_TRIPLES))

4596

In [44]:
len(EXTRACTED_TRIPLES[0])

107

In [14]:
BENCHMARK_DOCUMENTS = pd.read_csv(BENCHMARK_PATH[SELECTED_BENCHMARK_NAME]['documents'], sep=',')
BENCHMARK_QA = pd.read_csv(BENCHMARK_PATH[SELECTED_BENCHMARK_NAME]['qa'], sep=',')
print(BENCHMARK_DOCUMENTS.shape)
print(BENCHMARK_QA.shape)

(4596, 4)
(2000, 6)

In [12]:
BENCHMARK_DOCUMENTS.head()

,title,context,cntx_idx,hash
0,Polish-Russian War (film),Polish-Russian War (Wojna polsko-ruska) is a 2...,0,a23632c49331d3e7158a339adb16fdff
1,Xawery Żuławski,Xawery Żuławski (born 22 December 1971 in Wars...,1,03e78a2115c7401abe1985ca88ddc58e
2,Blind Shaft,Blind Shaft is a 2003 film about a pair of bru...,2,5f81eca1a49862947f6076fa910f5593
3,The Mask of Fu Manchu,The Mask of Fu Manchu is a 1932 pre-Code adven...,3,fbfd94b02d71d66981158e9de0e4a675
4,"John V, Prince of Anhalt-Zerbst","John V of Anhalt-Zerbst (Dessau, 4 September 1...",4,e046c19181bb7924533d964b34f72114

In [13]:
BENCHMARK_QA.head()

,question,type,answer,cntx_ids,qa_idx,original_qaidx
0,Who is the mother of the director of film Poli...,compositional,Małgorzata Braunek,"[0, 1]",0,0
1,"Which film came out first, Blind Shaft or The ...",comparison,The Mask Of Fu Manchu,"[2, 3]",1,1
2,"When did John V, Prince Of Anhalt-Zerbst's fat...",compositional,12 June 1516,"[4, 5]",2,2
3,What is the award that the director of film We...,compositional,Myanmar Motion Picture Academy Awards,"[6, 7]",3,3
4,Who is Charles Bretagne Marie De La Trémoille'...,inference,Charles Armand René de La Trémoille,"[8, 9]",4,5

In [69]:
EXTRACTED_TRIPLES_NODES_IDS: Dict = dict()
MATCHED_TNIDS_TO_QUESTIONS: List[Dict] = []

In [70]:
for idx in range(BENCHMARK_DOCUMENTS.shape[0]):
    cur_cntx_idx = BENCHMARK_DOCUMENTS['cntx_idx'][idx]
    cur_triples: List[Triplet] = EXTRACTED_TRIPLES[idx]

    uniques_object_nodes_info: Set[Tuple[str,str]] = set()
    uniques_thesis_nodes_info: Set[Tuple[str,str]] = set()
    unique_triples_ids: Dict[str, Set[str]] = defaultdict(set)
    tripletid_to_thesisid: Dict[str, str] = dict()
    for cur_triplet in cur_triples:
        if cur_triplet.start_node.type == NodeType.object:
            uniques_object_nodes_info.add((cur_triplet.start_node.id, cur_triplet.start_node.name))
        elif cur_triplet.start_node.type == NodeType.hyper:
            uniques_thesis_nodes_info.add((cur_triplet.start_node.id, cur_triplet.start_node.name))
            tripletid_to_thesisid[cur_triplet.id] = cur_triplet.start_node.id
        
        if cur_triplet.end_node.type == NodeType.object:
            uniques_object_nodes_info.add((cur_triplet.end_node.id, cur_triplet.end_node.name))
        elif cur_triplet.end_node.type == NodeType.hyper:
            uniques_thesis_nodes_info.add((cur_triplet.end_node.id, cur_triplet.end_node.name))
            tripletid_to_thesisid[cur_triplet.id] = cur_triplet.end_node.id
                    
        unique_triples_ids[cur_triplet.relation.type.value].add(cur_triplet.id)

    EXTRACTED_TRIPLES_NODES_IDS[int(cur_cntx_idx)] = {
        'unique_object_nodes_info': deepcopy(uniques_object_nodes_info),
        'uniques_thesis_nodes_info': deepcopy(uniques_thesis_nodes_info),
        'unique_triples_ids': deepcopy(dict(unique_triples_ids)),
        'tripletid_to_thesisid': deepcopy(tripletid_to_thesisid)
    }
EXTRACTED_TRIPLES_NODES_IDS = dict(EXTRACTED_TRIPLES_NODES_IDS)

In [71]:
len(EXTRACTED_TRIPLES_NODES_IDS)

4596

In [72]:
EXTRACTED_TRIPLES_NODES_IDS[0]

{'unique_object_nodes_info': {('01be28d032bfcda36f22b45ad3298bec',
   'last film'),
  ('175bcb21510404da1eb0458ac8dd5af3', 'kerwin mathews'),
  ('282f5dc7fac457d1217e4fd19918d158', 'andré hunebelle'),
  ('296cc9a02b167493f6ff885c48ca71ff', 'colour'),
  ('2bb937d2cf231c100f37e8cc7cc5a889', 'da. ma. cinematografica'),
  ('3910983de59d8413765574090521b4ad', 'international co-production'),
  ('3939151107d9f1c791788e164aba2db4', '74th oss 117 novel'),
  ('39dcaf7a053dc372fbc391d4e6b5d693', '1964'),
  ('3f77b7e9a85aa618e0aa5b2f998583e9', 'action scenes'),
  ('5436b6230ef21650b7e92de67d107650', 'first oss 117 film'),
  ('5f3fd601ca27ab1e58fd1286a8df0452', 'jean bruce'),
  ('7d87e4cbf6234bd3d6cbd59706af3603', 'co-production'),
  ('7f16109f1619fd7a733daf5a84c708c1', '1960'),
  ('8149ed381cb0798ec5643f0285d120c5', 'second oss 117 film'),
  ('83a1a1c1da46c00a08618d063a6abf11', 'shot'),
  ('8689391a8b93cd2d55ccf3f436eef4e2', 'thailand'),
  ('95cf9ab0cf87766af408a02c24aa1c11', 'production design'),
  ('a540047f2c0b4dc07825dd4de3b02af4', 'thai locations'),
  ('a6105c0a611b41b08f1209506350279e', 'yes'),
  ('a7c202868a1d804320d1ccd4201dcb87', 'claude carliez'),
  ('b77152d1135c55183497530c542ec56a', 'oss 117'),
  ('bab4ac375adad13f5693f24fceab7903', 'italy'),
  ('bda64bed7c078211fe179a6064805275', 'banco à bangkok pour oss 117'),
  ('bdbd6db1d8cc09a957e86180fda9442a', 'film'),
  ('cbbb2d2dc588004e6b28dfcaf35e46ce', 'eurospy spy-fi film'),
  ('d01baccd88842719b60b196893080f96', 'rené moulaert'),
  ('d41b226e08b4e4eef62147b21419a471', 'paul cadéac'),
  ('d638d193eb29ac87c0950ab36b80e0e8', 'novel'),
  ('e165d4f2174b66a7d1a95cb204d296eb', 'france'),
  ('e5c49842f300a6a16528341276f0a1dc', 'lila de calcutta'),
  ('eb90711f80f3f7190122971c8463cc0f', 'shadow of evil'),
  ('ef7d6a01720dcb1daade91bb267f5db7', '74th novel'),
  ('fd89784e59c72499525556f80289b2c7', 'production')},
 'uniques_thesis_nodes_info': {('15fb654d40e7b3f485befd391c9735a1',
   'shadow of evil was produced by paul cadéac'),
  ('1af6cf37be2b670234159b631029cfb4',
   'shadow of evil is the last film to star kerwin mathews as oss 117'),
  ('34429a7b2fc1dc7e065dcbfbce474389',
   'action scenes in the film were arranged by claude carliez'),
  ('4d694346c6a78daeaedb8c8fda5acaf0', 'the film was shot on thai locations'),
  ('67a522eefd5fb1a66111c5c035b2b47f',
   'production design for the film was done by rené moulaert'),
  ('6e9403b50b130a9b2fa0df0b97fbccf0', 'lila de calcutta is a 1960 novel'),
  ('6fec3b8fdcdc7234f9c5e8544d9c0c2d',
   "shadow of evil was based on jean bruce's novel lila de calcutta"),
  ('8820972bc7f35c8c00a99bca16d13b86',
   'banco à bangkok pour oss 117 released in usa as shadow of evil'),
  ('96a055ea51bbee8564976e442555b069',
   'shadow of evil is the first co-produced by da. ma. cinematografica'),
  ('ac2b42d5d504f51c776da5752cac6abf', 'shadow of evil is a 1964 film'),
  ('be4c4ff084e793b8497bdb2aa93f620c',
   'shadow of evil is an international co-production eurospy spy-fi film'),
  ('e5e697e2e511ce92e0e35e547506ffca',
   'shadow of evil is the first oss 117 film in colour'),
  ('f4ea289b6d4cdfefa92dbd4bafa24a2d',
   'shadow of evil is the 74th oss 117 novel adaptation'),
  ('f9b5e3844c1a4daecb6398118fdab19a',
   'shadow of evil is the second oss 117 film directed by andré hunebelle'),
  ('fe9ae07b2b531fca1f693b43a386cfea',
   'shadow of evil stars kerwin mathews as oss 117')},
 'unique_triples_ids': {'simple': {'070a9e9b7c894522cf9cebf533be2cd6',
   '09ec8a7fc3c63503ca2d8137ee045ba8',
   '0b172e5cd7205b765913e34bad2a3d78',
   '1a357505ed3ecfc900abb20bbb696b79',
   '1a9bec4238842082e154f9cef825510f',
   '25b0baaa732219046e405f812250997f',
   '3110a4486061bb8835dfd523972c2090',
   '409550ffaa3dccd519428a91c59bb1cc',
   '4d62d3aedbd7cd9b00bb73d63a1f87b4',
   '6c9ed593fc572ce7d8ece255f9c70924',
   '7c3490b6c0a64d70781d4c723e5f47e0',
   '7ccb5a84db3075adaeb461f0e3991e33',
   '8f456e7be4eaee18d7fd43513c096590',
   'ad6c2e6112604be2a1b516dba0ceb606',
   'f77bc321ba0fe0339f0b81fe132c3f6d'},
  'hyper': {'09c2a762ff917c949ec6105839caef81',
   '10f9eb0727809bb349e33aa61f546eae',
   '24026d77b36f5dfa3316c59675af4aa6',
   '264d81d6e9ea215f8e6bc33e62e77e41',
   '2d7a2c49ec5e605b1797db189bfca6da',
   '2e1ba8c5de446a8d6f64f36168c037d5',
   '41ea700986627196ea1c470a2b12ddc3',
   '47d0c420cec563a161e40d072f1db294',
   '53de51cae3fb7355d6b91a5a6431cd98',
   '582763d00bece36d6f729054234acd3e',
   '5d05d6543319bae9476b97fe5ef0b99d',
   '6020ca0a32fafd7b667b84710c795721',
   '6bc5122d5924f91ddbdb3abda63b978f',
   '6dbab8abc0fa9fd6a6b37dd40419efcf',
   '73a6b7f0a54ec58c942fd63876d7f519',
   '74e0696637564898154cc319acbefc7a',
   '7be36617d2bf399776f85f7c92dc75cd',
   '834cdec556c4d36fb14fa36d4b973e66',
   '8f8bfadf8373bb5b338767ffdf2e12f7',
   '9088977a028e5725a99bf2ea2303e1d3',
   '91cdda8c06fe0da5ee483b7e3193332a',
   '9393c42e4765e891832136b291373338',
   '98cbc85a437534dcb2e78145f9bd8ef6',
   '99c3e2a675643296349f27742781e255',
   'a024d9aed420b1ac406169a8e1b6dcf2',
   'ad78ea78a429389e2570fa76c55fec3a',
   'b132bf6cc31b536281b27e2b1d672a39',
   'b7959368dc8eb02f3fecaa837febf05f',
   'b98c36027fb679bb03778a6b86d8ccbc',
   'bd79d62ce8360c39d6ff02211d794ce8',
   'c8af93f3c78d78c483e76d7982dea80f',
   'cb18b8618020b8d83db134eaa626243d',
   'd14526ebfd2c1bcd34b988fc12dc55ad',
   'd4b03c86027cd894723308f73a66632a',
   'd7bf0a8c2b4990963afb50ae1c00e983',
   'd91a228934ce800490fcb79b01750216',
   'dc49fb6dd9b14b0dfb9975243d2b239c',
   'dccdaf8a579d3ece560a9e5999e4122c',
   'ddea8ef8251f6c5724596cc56279e327',
   'dfa7d7b8de032709a99a0518b2c9ed92',
   'e0af8664dedd82dc3b0633e75be0020a',
   'f08e082189e0057d228bdf1e1dc396f9',
   'f12ee082af964a668f8dc12ffb6dfc13',
   'f9d074f21f5e057bae1e2f75c8a1c1bb'},
  'episodic': {'091d101a7ed5106ce4e1bd846443d945',
   '0c37066c7acbde419c36eb59b88f5e2b',
   '1c04480c3d57412d9335bb699a154397',
   '1fdb64b647917663fb9327bf5fa7bb5d',
   '20065e4382e6c13d89c92156cc1b88ba',
   '3173c2e109d298b4b3b28d63aa64236e',
   '3cf269b74153813c66c34b5f17847b6f',
   '3ed9d7fec8eb065b720085a2f576afc4',
   '40b1bbd571df8bf178267b35df96863d',
   '4595af2527b833a699e2c851414bd671',
   '4755d31e3199dba74dc0c0e59d7df02a',
   '4a636f9282e25fd5b9225956424d3e43',
   '5039d5ec00388fb92752e34bba26bdff',
   '505a9d3ae1f69966e645b33159ac1cf8',
   '521e432f12609bd01f2cffabbd911085',
   '60c7b20fdf19edea20663abc9df1a386',
   '6c96e2bdd834f37890fc01da65bdc1d7',
   '6ff625da18bff42fe349e781f1169a46',
   '719782e6fd4ee260b580ff6ab162c7b2',
   '7278bcc3805a1e573dd27ead23626b4d',
   '731dd45a81a538fe1695062c07847511',
   '77a615cbaefa14de7ea5b1b5fccf8480',
   '7a45d6815fb2d6e1c30d1be35c4f45bb',
   '85a5ea558583b8547b238d367f58233d',
   '8761a944161982ff087c6200ded0af5a',
   '8ebe95dc913c15da2bbb391e18098729',
   '92f11f9d13672ea167e0390101539c04',
   '93f8ee71abc9162c4a606826b257950f',
   'a3359816a3068b9cd6c72cf782f96145',
   'addcc2e1657e566c7338f9ede07330ef',
   'ae19b4ac3fc289b3f0c928f9569e8c52',
   'b75825af816fd10376d845e4fda121a4',
   'b965f921b43cd33c59be7f0f0c893f01',
   'ba75f8917b56511286f684c4a74869f5',
   'c05c9edd4aee99b523ce380e0af10048',
   'c43ea1fccd3f4823dfff869f57890fdc',
   'c5d7153591f244a96ac81655d9e8d012',
   'd349a85d08e93cbc05507abe751f2582',
   'd38efd4457b9823655a575065cddb320',
   'd42835388f571ecda4a00eb3bffa4b03',
   'd6f49f0d6626f8ace875377d1aca70a4',
   'd7e0c48d7ad1e819431aa6cf955ee1d3',
   'd91695c66b329911594065aa834e4019',
   'de2d0e12c474907ef67271c73d3d0a7e',
   'e7f719dd3615e42a26c2496ca8b3401b',
   'f7462e1784dee5fec9aa3d91eff3c5a4',
   'f8435247965bed14eb11167e1407b2ef',
   'fce4770ef1a76c846a44203c5fac7bdf'}},
 'tripletid_to_thesisid': {'d7bf0a8c2b4990963afb50ae1c00e983': '8820972bc7f35c8c00a99bca16d13b86',
  '8f8bfadf8373bb5b338767ffdf2e12f7': '8820972bc7f35c8c00a99bca16d13b86',
  '264d81d6e9ea215f8e6bc33e62e77e41': 'ac2b42d5d504f51c776da5752cac6abf',
  'd91a228934ce800490fcb79b01750216': 'ac2b42d5d504f51c776da5752cac6abf',
  'b132bf6cc31b536281b27e2b1d672a39': 'ac2b42d5d504f51c776da5752cac6abf',
  '9088977a028e5725a99bf2ea2303e1d3': 'be4c4ff084e793b8497bdb2aa93f620c',
  '41ea700986627196ea1c470a2b12ddc3': 'be4c4ff084e793b8497bdb2aa93f620c',
  '24026d77b36f5dfa3316c59675af4aa6': 'be4c4ff084e793b8497bdb2aa93f620c',
  '9393c42e4765e891832136b291373338': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  'bd79d62ce8360c39d6ff02211d794ce8': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '6bc5122d5924f91ddbdb3abda63b978f': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '09c2a762ff917c949ec6105839caef81': '6e9403b50b130a9b2fa0df0b97fbccf0',
  'c8af93f3c78d78c483e76d7982dea80f': '6e9403b50b130a9b2fa0df0b97fbccf0',
  'b98c36027fb679bb03778a6b86d8ccbc': '6e9403b50b130a9b2fa0df0b97fbccf0',
  '6dbab8abc0fa9fd6a6b37dd40419efcf': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'a024d9aed420b1ac406169a8e1b6dcf2': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'f08e082189e0057d228bdf1e1dc396f9': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  '2e1ba8c5de446a8d6f64f36168c037d5': 'f9b5e3844c1a4daecb6398118fdab19a',
  '834cdec556c4d36fb14fa36d4b973e66': 'f9b5e3844c1a4daecb6398118fdab19a',
  '74e0696637564898154cc319acbefc7a': 'f9b5e3844c1a4daecb6398118fdab19a',
  'dc49fb6dd9b14b0dfb9975243d2b239c': '15fb654d40e7b3f485befd391c9735a1',
  'cb18b8618020b8d83db134eaa626243d': '15fb654d40e7b3f485befd391c9735a1',
  '47d0c420cec563a161e40d072f1db294': '15fb654d40e7b3f485befd391c9735a1',
  'b7959368dc8eb02f3fecaa837febf05f': 'e5e697e2e511ce92e0e35e547506ffca',
  '99c3e2a675643296349f27742781e255': 'e5e697e2e511ce92e0e35e547506ffca',
  '10f9eb0727809bb349e33aa61f546eae': 'e5e697e2e511ce92e0e35e547506ffca',
  'e0af8664dedd82dc3b0633e75be0020a': '96a055ea51bbee8564976e442555b069',
  'ddea8ef8251f6c5724596cc56279e327': '96a055ea51bbee8564976e442555b069',
  'd4b03c86027cd894723308f73a66632a': '96a055ea51bbee8564976e442555b069',
  '98cbc85a437534dcb2e78145f9bd8ef6': 'fe9ae07b2b531fca1f693b43a386cfea',
  '73a6b7f0a54ec58c942fd63876d7f519': 'fe9ae07b2b531fca1f693b43a386cfea',
  '6020ca0a32fafd7b667b84710c795721': 'fe9ae07b2b531fca1f693b43a386cfea',
  '53de51cae3fb7355d6b91a5a6431cd98': '1af6cf37be2b670234159b631029cfb4',
  'd14526ebfd2c1bcd34b988fc12dc55ad': '1af6cf37be2b670234159b631029cfb4',
  '2d7a2c49ec5e605b1797db189bfca6da': '1af6cf37be2b670234159b631029cfb4',
  'f9d074f21f5e057bae1e2f75c8a1c1bb': '4d694346c6a78daeaedb8c8fda5acaf0',
  '7be36617d2bf399776f85f7c92dc75cd': '4d694346c6a78daeaedb8c8fda5acaf0',
  'dccdaf8a579d3ece560a9e5999e4122c': '4d694346c6a78daeaedb8c8fda5acaf0',
  'dfa7d7b8de032709a99a0518b2c9ed92': '34429a7b2fc1dc7e065dcbfbce474389',
  '91cdda8c06fe0da5ee483b7e3193332a': '34429a7b2fc1dc7e065dcbfbce474389',
  '582763d00bece36d6f729054234acd3e': '34429a7b2fc1dc7e065dcbfbce474389',
  'f12ee082af964a668f8dc12ffb6dfc13': '67a522eefd5fb1a66111c5c035b2b47f',
  'ad78ea78a429389e2570fa76c55fec3a': '67a522eefd5fb1a66111c5c035b2b47f',
  '5d05d6543319bae9476b97fe5ef0b99d': '67a522eefd5fb1a66111c5c035b2b47f',
  'd6f49f0d6626f8ace875377d1aca70a4': '8820972bc7f35c8c00a99bca16d13b86',
  '521e432f12609bd01f2cffabbd911085': 'ac2b42d5d504f51c776da5752cac6abf',
  'f8435247965bed14eb11167e1407b2ef': 'be4c4ff084e793b8497bdb2aa93f620c',
  '8ebe95dc913c15da2bbb391e18098729': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '77a615cbaefa14de7ea5b1b5fccf8480': '6e9403b50b130a9b2fa0df0b97fbccf0',
  '92f11f9d13672ea167e0390101539c04': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'c43ea1fccd3f4823dfff869f57890fdc': 'f9b5e3844c1a4daecb6398118fdab19a',
  '0c37066c7acbde419c36eb59b88f5e2b': '15fb654d40e7b3f485befd391c9735a1',
  'b965f921b43cd33c59be7f0f0c893f01': 'e5e697e2e511ce92e0e35e547506ffca',
  'd38efd4457b9823655a575065cddb320': '96a055ea51bbee8564976e442555b069',
  'd7e0c48d7ad1e819431aa6cf955ee1d3': 'fe9ae07b2b531fca1f693b43a386cfea',
  'f7462e1784dee5fec9aa3d91eff3c5a4': '1af6cf37be2b670234159b631029cfb4',
  'c05c9edd4aee99b523ce380e0af10048': '4d694346c6a78daeaedb8c8fda5acaf0',
  '1c04480c3d57412d9335bb699a154397': '34429a7b2fc1dc7e065dcbfbce474389',
  '20065e4382e6c13d89c92156cc1b88ba': '67a522eefd5fb1a66111c5c035b2b47f'}}

In [73]:
for idx in range(BENCHMARK_QA.shape[0]):
    qa_idx = BENCHMARK_QA['qa_idx'][idx]
    relevant_cntx_idxs = ast.literal_eval(BENCHMARK_QA['cntx_ids'][idx])

    uniques_object_nodes_info: Set[Tuple[str,str]] = set()
    uniques_thesis_nodes_info: Set[Tuple[str,str]] = set()
    unique_triples_ids: Dict[str, Set[str]] = defaultdict(set)
    tripletid_to_thesisid: Dict[str, str] = dict()

    for cur_cntx_idx in relevant_cntx_idxs:
        uniques_object_nodes_info.update(EXTRACTED_TRIPLES_NODES_IDS[cur_cntx_idx]['unique_object_nodes_info'])
        uniques_thesis_nodes_info.update(EXTRACTED_TRIPLES_NODES_IDS[cur_cntx_idx]['uniques_thesis_nodes_info'])
        tripletid_to_thesisid.update(EXTRACTED_TRIPLES_NODES_IDS[cur_cntx_idx]['tripletid_to_thesisid'])
        for k, v in EXTRACTED_TRIPLES_NODES_IDS[cur_cntx_idx]['unique_triples_ids'].items():
            unique_triples_ids[k].update(v)


    MATCHED_TNIDS_TO_QUESTIONS.append({
        'qa_idx': int(qa_idx),
        'question': BENCHMARK_QA['question'][idx],
        'cntx_idxs': deepcopy(relevant_cntx_idxs),
        'relevant_unique_object_nodes_info': deepcopy(uniques_object_nodes_info),
        'relevant_unique_thesis_nodes_info': deepcopy(uniques_thesis_nodes_info),
        'relevant_tripletid_to_thesisid': deepcopy(tripletid_to_thesisid),
        'relevant_unique_triples_ids': deepcopy(dict(unique_triples_ids))
    })

In [74]:
print(len(MATCHED_TNIDS_TO_QUESTIONS))

2000

In [75]:
MATCHED_TNIDS_TO_QUESTIONS[0]

{'qa_idx': 0,
 'question': 'Who is the mother of the director of film Polish-Russian War (Film)?',
 'cntx_idxs': [0, 1],
 'relevant_unique_object_nodes_info': {('01be28d032bfcda36f22b45ad3298bec',
   'last film'),
  ('0302cdd79c48c15830805aba44f35d5a', 'mystery science theater 3000'),
  ('175bcb21510404da1eb0458ac8dd5af3', 'kerwin mathews'),
  ('23a58bf9274bedb19375e527a0744fa9', 'with'),
  ('282f5dc7fac457d1217e4fd19918d158', 'andré hunebelle'),
  ('296cc9a02b167493f6ff885c48ca71ff', 'colour'),
  ('2bb937d2cf231c100f37e8cc7cc5a889', 'da. ma. cinematografica'),
  ('2cf594c51ff9e6dcbc78e42313671e43', 'comedy central'),
  ('3910983de59d8413765574090521b4ad', 'international co-production'),
  ('3939151107d9f1c791788e164aba2db4', '74th oss 117 novel'),
  ('39dcaf7a053dc372fbc391d4e6b5d693', '1964'),
  ('3b2eb19d98fa94a5794f3d6949cf6020', 'herschell gordon lewis'),
  ('3f77b7e9a85aa618e0aa5b2f998583e9', 'action scenes'),
  ('4460740cd9ee7f43a4fde3a966f0787d', 'horror'),
  ('5436b6230ef21650b7e92de67d107650', 'first oss 117 film'),
  ('5bfdb4537c1637cee9bfe779b8b2dfa0', 'uncredited'),
  ('5f3fd601ca27ab1e58fd1286a8df0452', 'jean bruce'),
  ('7c994c3fb728874ff5bb1b9a731f3966', 'american'),
  ('7d87e4cbf6234bd3d6cbd59706af3603', 'co-production'),
  ('7f16109f1619fd7a733daf5a84c708c1', '1960'),
  ('8149ed381cb0798ec5643f0285d120c5', 'second oss 117 film'),
  ('83a1a1c1da46c00a08618d063a6abf11', 'shot'),
  ('8689391a8b93cd2d55ccf3f436eef4e2', 'thailand'),
  ('930f5e6af9b1b1dbb8d9fad80faa40e8', 'science-fiction'),
  ('95cf9ab0cf87766af408a02c24aa1c11', 'production design'),
  ('a4bc002f7d77e57ce35a67b521d96881', 'directed by'),
  ('a540047f2c0b4dc07825dd4de3b02af4', 'thai locations'),
  ('a6105c0a611b41b08f1209506350279e', 'yes'),
  ('a6a5196ce03a7bb9375a1b4835406d69', 'monster a go-go'),
  ('a7c202868a1d804320d1ccd4201dcb87', 'claude carliez'),
  ('a9e07314d6df792bc2c5d5f3e579b475', 'science-fiction horror'),
  ('af14b067a4804cdc758bf5ba6908a3fb', 'association'),
  ('b77152d1135c55183497530c542ec56a', 'oss 117'),
  ('bab4ac375adad13f5693f24fceab7903', 'italy'),
  ('bda64bed7c078211fe179a6064805275', 'banco à bangkok pour oss 117'),
  ('bdbd6db1d8cc09a957e86180fda9442a', 'film'),
  ('c5a4e7e6882845ea7bb4d9462868219b', '1993'),
  ('c9e661c6cd0e6e343ae44fbf34c16b6e', 'considered'),
  ('cbbb2d2dc588004e6b28dfcaf35e46ce', 'eurospy spy-fi film'),
  ('d01baccd88842719b60b196893080f96', 'rené moulaert'),
  ('d3b151a0067951ff581794fb72db64ee', 'bill rebane'),
  ('d41b226e08b4e4eef62147b21419a471', 'paul cadéac'),
  ('d46e1fcf4c07ce4a69ee07e4134bcef1', '1965'),
  ('d638d193eb29ac87c0950ab36b80e0e8', 'novel'),
  ('e165d4f2174b66a7d1a95cb204d296eb', 'france'),
  ('e5c49842f300a6a16528341276f0a1dc', 'lila de calcutta'),
  ('eb90711f80f3f7190122971c8463cc0f', 'shadow of evil'),
  ('ef78ff1c2422f240e1dde17b9b0ccc98', 'one of the worst films ever made'),
  ('ef7d6a01720dcb1daade91bb267f5db7', '74th novel'),
  ('fd89784e59c72499525556f80289b2c7', 'production')},
 'relevant_unique_thesis_nodes_info': {('0e78fa8232f147bed30c8a47e228869d',
   'monster a go-go is considered one of the worst films ever made'),
  ('15fb654d40e7b3f485befd391c9735a1',
   'shadow of evil was produced by paul cadéac'),
  ('1af6cf37be2b670234159b631029cfb4',
   'shadow of evil is the last film to star kerwin mathews as oss 117'),
  ('34429a7b2fc1dc7e065dcbfbce474389',
   'action scenes in the film were arranged by claude carliez'),
  ('4d694346c6a78daeaedb8c8fda5acaf0', 'the film was shot on thai locations'),
  ('4f1017bde80dd3f7d4b7174ffe59dd35',
   'monster a go-go is a 1965 american science-fiction horror film'),
  ('67a522eefd5fb1a66111c5c035b2b47f',
   'production design for the film was done by rené moulaert'),
  ('6e9403b50b130a9b2fa0df0b97fbccf0', 'lila de calcutta is a 1960 novel'),
  ('6fec3b8fdcdc7234f9c5e8544d9c0c2d',
   "shadow of evil was based on jean bruce's novel lila de calcutta"),
  ('8820972bc7f35c8c00a99bca16d13b86',
   'banco à bangkok pour oss 117 released in usa as shadow of evil'),
  ('88f4a562e4c4a4381c9d7e60649dd3a0',
   'monster a go-go was directed by bill rebane and herschell gordon lewis'),
  ('96a055ea51bbee8564976e442555b069',
   'shadow of evil is the first co-produced by da. ma. cinematografica'),
  ('a86a86449e8020c25d90df3fa2a9d95e',
   'in 1993, monster a go-go was featured in an episode of mystery science theater 3000 on comedy central'),
  ('ac2b42d5d504f51c776da5752cac6abf', 'shadow of evil is a 1964 film'),
  ('be4c4ff084e793b8497bdb2aa93f620c',
   'shadow of evil is an international co-production eurospy spy-fi film'),
  ('e5e697e2e511ce92e0e35e547506ffca',
   'shadow of evil is the first oss 117 film in colour'),
  ('eceb651ae0962d3785ae76e4c56a5047',
   'bill rebane and herschell gordon lewis were uncredited in association with this film'),
  ('f4ea289b6d4cdfefa92dbd4bafa24a2d',
   'shadow of evil is the 74th oss 117 novel adaptation'),
  ('f9b5e3844c1a4daecb6398118fdab19a',
   'shadow of evil is the second oss 117 film directed by andré hunebelle'),
  ('fe9ae07b2b531fca1f693b43a386cfea',
   'shadow of evil stars kerwin mathews as oss 117')},
 'relevant_tripletid_to_thesisid': {'d7bf0a8c2b4990963afb50ae1c00e983': '8820972bc7f35c8c00a99bca16d13b86',
  '8f8bfadf8373bb5b338767ffdf2e12f7': '8820972bc7f35c8c00a99bca16d13b86',
  '264d81d6e9ea215f8e6bc33e62e77e41': 'ac2b42d5d504f51c776da5752cac6abf',
  'd91a228934ce800490fcb79b01750216': 'ac2b42d5d504f51c776da5752cac6abf',
  'b132bf6cc31b536281b27e2b1d672a39': 'ac2b42d5d504f51c776da5752cac6abf',
  '9088977a028e5725a99bf2ea2303e1d3': 'be4c4ff084e793b8497bdb2aa93f620c',
  '41ea700986627196ea1c470a2b12ddc3': 'be4c4ff084e793b8497bdb2aa93f620c',
  '24026d77b36f5dfa3316c59675af4aa6': 'be4c4ff084e793b8497bdb2aa93f620c',
  '9393c42e4765e891832136b291373338': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  'bd79d62ce8360c39d6ff02211d794ce8': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '6bc5122d5924f91ddbdb3abda63b978f': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '09c2a762ff917c949ec6105839caef81': '6e9403b50b130a9b2fa0df0b97fbccf0',
  'c8af93f3c78d78c483e76d7982dea80f': '6e9403b50b130a9b2fa0df0b97fbccf0',
  'b98c36027fb679bb03778a6b86d8ccbc': '6e9403b50b130a9b2fa0df0b97fbccf0',
  '6dbab8abc0fa9fd6a6b37dd40419efcf': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'a024d9aed420b1ac406169a8e1b6dcf2': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'f08e082189e0057d228bdf1e1dc396f9': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  '2e1ba8c5de446a8d6f64f36168c037d5': 'f9b5e3844c1a4daecb6398118fdab19a',
  '834cdec556c4d36fb14fa36d4b973e66': 'f9b5e3844c1a4daecb6398118fdab19a',
  '74e0696637564898154cc319acbefc7a': 'f9b5e3844c1a4daecb6398118fdab19a',
  'dc49fb6dd9b14b0dfb9975243d2b239c': '15fb654d40e7b3f485befd391c9735a1',
  'cb18b8618020b8d83db134eaa626243d': '15fb654d40e7b3f485befd391c9735a1',
  '47d0c420cec563a161e40d072f1db294': '15fb654d40e7b3f485befd391c9735a1',
  'b7959368dc8eb02f3fecaa837febf05f': 'e5e697e2e511ce92e0e35e547506ffca',
  '99c3e2a675643296349f27742781e255': 'e5e697e2e511ce92e0e35e547506ffca',
  '10f9eb0727809bb349e33aa61f546eae': 'e5e697e2e511ce92e0e35e547506ffca',
  'e0af8664dedd82dc3b0633e75be0020a': '96a055ea51bbee8564976e442555b069',
  'ddea8ef8251f6c5724596cc56279e327': '96a055ea51bbee8564976e442555b069',
  'd4b03c86027cd894723308f73a66632a': '96a055ea51bbee8564976e442555b069',
  '98cbc85a437534dcb2e78145f9bd8ef6': 'fe9ae07b2b531fca1f693b43a386cfea',
  '73a6b7f0a54ec58c942fd63876d7f519': 'fe9ae07b2b531fca1f693b43a386cfea',
  '6020ca0a32fafd7b667b84710c795721': 'fe9ae07b2b531fca1f693b43a386cfea',
  '53de51cae3fb7355d6b91a5a6431cd98': '1af6cf37be2b670234159b631029cfb4',
  'd14526ebfd2c1bcd34b988fc12dc55ad': '1af6cf37be2b670234159b631029cfb4',
  '2d7a2c49ec5e605b1797db189bfca6da': '1af6cf37be2b670234159b631029cfb4',
  'f9d074f21f5e057bae1e2f75c8a1c1bb': '4d694346c6a78daeaedb8c8fda5acaf0',
  '7be36617d2bf399776f85f7c92dc75cd': '4d694346c6a78daeaedb8c8fda5acaf0',
  'dccdaf8a579d3ece560a9e5999e4122c': '4d694346c6a78daeaedb8c8fda5acaf0',
  'dfa7d7b8de032709a99a0518b2c9ed92': '34429a7b2fc1dc7e065dcbfbce474389',
  '91cdda8c06fe0da5ee483b7e3193332a': '34429a7b2fc1dc7e065dcbfbce474389',
  '582763d00bece36d6f729054234acd3e': '34429a7b2fc1dc7e065dcbfbce474389',
  'f12ee082af964a668f8dc12ffb6dfc13': '67a522eefd5fb1a66111c5c035b2b47f',
  'ad78ea78a429389e2570fa76c55fec3a': '67a522eefd5fb1a66111c5c035b2b47f',
  '5d05d6543319bae9476b97fe5ef0b99d': '67a522eefd5fb1a66111c5c035b2b47f',
  'd6f49f0d6626f8ace875377d1aca70a4': '8820972bc7f35c8c00a99bca16d13b86',
  '521e432f12609bd01f2cffabbd911085': 'ac2b42d5d504f51c776da5752cac6abf',
  'f8435247965bed14eb11167e1407b2ef': 'be4c4ff084e793b8497bdb2aa93f620c',
  '8ebe95dc913c15da2bbb391e18098729': '6fec3b8fdcdc7234f9c5e8544d9c0c2d',
  '77a615cbaefa14de7ea5b1b5fccf8480': '6e9403b50b130a9b2fa0df0b97fbccf0',
  '92f11f9d13672ea167e0390101539c04': 'f4ea289b6d4cdfefa92dbd4bafa24a2d',
  'c43ea1fccd3f4823dfff869f57890fdc': 'f9b5e3844c1a4daecb6398118fdab19a',
  '0c37066c7acbde419c36eb59b88f5e2b': '15fb654d40e7b3f485befd391c9735a1',
  'b965f921b43cd33c59be7f0f0c893f01': 'e5e697e2e511ce92e0e35e547506ffca',
  'd38efd4457b9823655a575065cddb320': '96a055ea51bbee8564976e442555b069',
  'd7e0c48d7ad1e819431aa6cf955ee1d3': 'fe9ae07b2b531fca1f693b43a386cfea',
  'f7462e1784dee5fec9aa3d91eff3c5a4': '1af6cf37be2b670234159b631029cfb4',
  'c05c9edd4aee99b523ce380e0af10048': '4d694346c6a78daeaedb8c8fda5acaf0',
  '1c04480c3d57412d9335bb699a154397': '34429a7b2fc1dc7e065dcbfbce474389',
  '20065e4382e6c13d89c92156cc1b88ba': '67a522eefd5fb1a66111c5c035b2b47f',
  'e2f69af6699ed9fc0676d1db614063c9': '4f1017bde80dd3f7d4b7174ffe59dd35',
  'fbef7e25f2a40f83c47c806de1c11b2c': '4f1017bde80dd3f7d4b7174ffe59dd35',
  '5220bf07b4b4aec0ea4a5925f5d4851e': '4f1017bde80dd3f7d4b7174ffe59dd35',
  'b067b4d09ac0a78f1e2ba6c38b7caabe': '4f1017bde80dd3f7d4b7174ffe59dd35',
  '8a81a60440feb1d266b01575a63e2707': '4f1017bde80dd3f7d4b7174ffe59dd35',
  '75ff57f50ec9f4e56bef62060b4158df': '4f1017bde80dd3f7d4b7174ffe59dd35',
  '2ac31bf527d7dad0af85d934973df112': '88f4a562e4c4a4381c9d7e60649dd3a0',
  'ed8998f47878cce806b26bd5b7041c13': '88f4a562e4c4a4381c9d7e60649dd3a0',
  '2520d588204aa37dd4d4af2790c3319e': '88f4a562e4c4a4381c9d7e60649dd3a0',
  '9b8c00b1835d48b41debe6a00eef3ee7': '88f4a562e4c4a4381c9d7e60649dd3a0',
  '53496b31f5aba13824eb57e3687377e7': 'eceb651ae0962d3785ae76e4c56a5047',
  '9d61f335b3907f1c0d3af644e8df03d4': 'eceb651ae0962d3785ae76e4c56a5047',
  'f1a031097dcebf0e88a7398edb659707': 'eceb651ae0962d3785ae76e4c56a5047',
  '390d645ddd25c53e5f465a3694cb4ae2': 'eceb651ae0962d3785ae76e4c56a5047',
  '665149a06c79f67889622779ef620dc8': 'eceb651ae0962d3785ae76e4c56a5047',
  '55d859b7081719342ab078e3d59d6458': 'eceb651ae0962d3785ae76e4c56a5047',
  'b055d15cd90a453a1e399cd0443bff93': '0e78fa8232f147bed30c8a47e228869d',
  '2df0fccf19fc014affaad5cad05dde44': '0e78fa8232f147bed30c8a47e228869d',
  'ba193ea3c614e951c54c2aa6fdf43bc4': '0e78fa8232f147bed30c8a47e228869d',
  'c1e388339775dcdd8e49fff292f2ed23': 'a86a86449e8020c25d90df3fa2a9d95e',
  '818015536c73b159acd38d5ffec16de0': 'a86a86449e8020c25d90df3fa2a9d95e',
  '03319e4a8c50d7e301b8bedd16c6f265': 'a86a86449e8020c25d90df3fa2a9d95e',
  '263a5cf815426afef9446b6cd2104cd8': 'a86a86449e8020c25d90df3fa2a9d95e',
  '2f821ec4ff2ff16f103fb32df2e20d01': '4f1017bde80dd3f7d4b7174ffe59dd35',
  '25eaaec06916f8576a7f34c62411d510': '88f4a562e4c4a4381c9d7e60649dd3a0',
  '2fb523a0772dd27f5c6c46fd10f20ad6': 'eceb651ae0962d3785ae76e4c56a5047',
  '4edd2e2c4143d127f6c0caca97f8c7bd': '0e78fa8232f147bed30c8a47e228869d',
  '7abb1e986b3a64e3a52fa5fd18683710': 'a86a86449e8020c25d90df3fa2a9d95e'},
 'relevant_unique_triples_ids': {'simple': {'070a9e9b7c894522cf9cebf533be2cd6',
   '09ec8a7fc3c63503ca2d8137ee045ba8',
   '0b172e5cd7205b765913e34bad2a3d78',
   '1871ff01e3b79cca2bf8b177895b220e',
   '1a357505ed3ecfc900abb20bbb696b79',
   '1a9bec4238842082e154f9cef825510f',
   '24aea11cd45299a40721d90bb841d7ef',
   '25b0baaa732219046e405f812250997f',
   '3110a4486061bb8835dfd523972c2090',
   '409550ffaa3dccd519428a91c59bb1cc',
   '4d62d3aedbd7cd9b00bb73d63a1f87b4',
   '50b715419ca6df73f2c44d24ae64e056',
   '545623c0f258adb1c0583f4ea44f617e',
   '6c9ed593fc572ce7d8ece255f9c70924',
   '7c3490b6c0a64d70781d4c723e5f47e0',
   '7ccb5a84db3075adaeb461f0e3991e33',
   '8f456e7be4eaee18d7fd43513c096590',
   '8fcae8f6a0160fdd09e0708a9fdd93d0',
   'ad6c2e6112604be2a1b516dba0ceb606',
   'b8dd5047203c30e5d581452b667f67ff',
   'ba31fb73b51be1a4f7a19b7e46df7150',
   'd62e4c21cefa1b1caca2251eb6a94aba',
   'f77bc321ba0fe0339f0b81fe132c3f6d'},
  'hyper': {'03319e4a8c50d7e301b8bedd16c6f265',
   '09c2a762ff917c949ec6105839caef81',
   '10f9eb0727809bb349e33aa61f546eae',
   '24026d77b36f5dfa3316c59675af4aa6',
   '2520d588204aa37dd4d4af2790c3319e',
   '263a5cf815426afef9446b6cd2104cd8',
   '264d81d6e9ea215f8e6bc33e62e77e41',
   '2ac31bf527d7dad0af85d934973df112',
   '2d7a2c49ec5e605b1797db189bfca6da',
   '2df0fccf19fc014affaad5cad05dde44',
   '2e1ba8c5de446a8d6f64f36168c037d5',
   '390d645ddd25c53e5f465a3694cb4ae2',
   '41ea700986627196ea1c470a2b12ddc3',
   '47d0c420cec563a161e40d072f1db294',
   '5220bf07b4b4aec0ea4a5925f5d4851e',
   '53496b31f5aba13824eb57e3687377e7',
   '53de51cae3fb7355d6b91a5a6431cd98',
   '55d859b7081719342ab078e3d59d6458',
   '582763d00bece36d6f729054234acd3e',
   '5d05d6543319bae9476b97fe5ef0b99d',
   '6020ca0a32fafd7b667b84710c795721',
   '665149a06c79f67889622779ef620dc8',
   '6bc5122d5924f91ddbdb3abda63b978f',
   '6dbab8abc0fa9fd6a6b37dd40419efcf',
   '73a6b7f0a54ec58c942fd63876d7f519',
   '74e0696637564898154cc319acbefc7a',
   '75ff57f50ec9f4e56bef62060b4158df',
   '7be36617d2bf399776f85f7c92dc75cd',
   '818015536c73b159acd38d5ffec16de0',
   '834cdec556c4d36fb14fa36d4b973e66',
   '8a81a60440feb1d266b01575a63e2707',
   '8f8bfadf8373bb5b338767ffdf2e12f7',
   '9088977a028e5725a99bf2ea2303e1d3',
   '91cdda8c06fe0da5ee483b7e3193332a',
   '9393c42e4765e891832136b291373338',
   '98cbc85a437534dcb2e78145f9bd8ef6',
   '99c3e2a675643296349f27742781e255',
   '9b8c00b1835d48b41debe6a00eef3ee7',
   '9d61f335b3907f1c0d3af644e8df03d4',
   'a024d9aed420b1ac406169a8e1b6dcf2',
   'ad78ea78a429389e2570fa76c55fec3a',
   'b055d15cd90a453a1e399cd0443bff93',
   'b067b4d09ac0a78f1e2ba6c38b7caabe',
   'b132bf6cc31b536281b27e2b1d672a39',
   'b7959368dc8eb02f3fecaa837febf05f',
   'b98c36027fb679bb03778a6b86d8ccbc',
   'ba193ea3c614e951c54c2aa6fdf43bc4',
   'bd79d62ce8360c39d6ff02211d794ce8',
   'c1e388339775dcdd8e49fff292f2ed23',
   'c8af93f3c78d78c483e76d7982dea80f',
   'cb18b8618020b8d83db134eaa626243d',
   'd14526ebfd2c1bcd34b988fc12dc55ad',
   'd4b03c86027cd894723308f73a66632a',
   'd7bf0a8c2b4990963afb50ae1c00e983',
   'd91a228934ce800490fcb79b01750216',
   'dc49fb6dd9b14b0dfb9975243d2b239c',
   'dccdaf8a579d3ece560a9e5999e4122c',
   'ddea8ef8251f6c5724596cc56279e327',
   'dfa7d7b8de032709a99a0518b2c9ed92',
   'e0af8664dedd82dc3b0633e75be0020a',
   'e2f69af6699ed9fc0676d1db614063c9',
   'ed8998f47878cce806b26bd5b7041c13',
   'f08e082189e0057d228bdf1e1dc396f9',
   'f12ee082af964a668f8dc12ffb6dfc13',
   'f1a031097dcebf0e88a7398edb659707',
   'f9d074f21f5e057bae1e2f75c8a1c1bb',
   'fbef7e25f2a40f83c47c806de1c11b2c'},
  'episodic': {'0520561a88545321cb94f982069c4c3a',
   '091d101a7ed5106ce4e1bd846443d945',
   '0a7a3361c5e6361102eac5e4bfe7e748',
   '0c37066c7acbde419c36eb59b88f5e2b',
   '0fe3a856a9cd520b6e2ce47600fa56a9',
   '1c04480c3d57412d9335bb699a154397',
   '1fdb64b647917663fb9327bf5fa7bb5d',
   '20065e4382e6c13d89c92156cc1b88ba',
   '23153325da65d3ae63f575e46eea16c3',
   '25eaaec06916f8576a7f34c62411d510',
   '2f821ec4ff2ff16f103fb32df2e20d01',
   '2fb523a0772dd27f5c6c46fd10f20ad6',
   '313bd6aa038c150fcbbb58e569a34829',
   '3173c2e109d298b4b3b28d63aa64236e',
   '3cf269b74153813c66c34b5f17847b6f',
   '3ed9d7fec8eb065b720085a2f576afc4',
   '40b1bbd571df8bf178267b35df96863d',
   '43de0d516a6ab2160319a21376c0f2fb',
   '4595af2527b833a699e2c851414bd671',
   '4755d31e3199dba74dc0c0e59d7df02a',
   '491272e12096eb5f6558637bcd1c35e6',
   '4a636f9282e25fd5b9225956424d3e43',
   '4d2ca0c9a579cf2a77d470241e8e356c',
   '4edd2e2c4143d127f6c0caca97f8c7bd',
   '5039d5ec00388fb92752e34bba26bdff',
   '505a9d3ae1f69966e645b33159ac1cf8',
   '521e432f12609bd01f2cffabbd911085',
   '5fe03a9294690ad4a0c1cd9997ac82b9',
   '60c7b20fdf19edea20663abc9df1a386',
   '6c96e2bdd834f37890fc01da65bdc1d7',
   '6ff625da18bff42fe349e781f1169a46',
   '719782e6fd4ee260b580ff6ab162c7b2',
   '7278bcc3805a1e573dd27ead23626b4d',
   '731dd45a81a538fe1695062c07847511',
   '77a615cbaefa14de7ea5b1b5fccf8480',
   '7a45d6815fb2d6e1c30d1be35c4f45bb',
   '7abb1e986b3a64e3a52fa5fd18683710',
   '85a5ea558583b8547b238d367f58233d',
   '8761a944161982ff087c6200ded0af5a',
   '8de067fcd0231ab035723ebec139d8d3',
   '8ebe95dc913c15da2bbb391e18098729',
   '92f11f9d13672ea167e0390101539c04',
   '93f8ee71abc9162c4a606826b257950f',
   'a3359816a3068b9cd6c72cf782f96145',
   'aa01ae3691aab54291598517d5a0dd89',
   'ad58ed68be352e2dfe5ec6666c722ebd',
   'addcc2e1657e566c7338f9ede07330ef',
   'ae19b4ac3fc289b3f0c928f9569e8c52',
   'ae85c2e238c8c460f4b93aecf7d08ad4',
   'af56573468eb52712d71606369ba0eec',
   'b046f54a8b79a6175258a6a7f7d5aa2f',
   'b0c66e7e47db4c1fe965fcbf78966a6e',
   'b75825af816fd10376d845e4fda121a4',
   'b965f921b43cd33c59be7f0f0c893f01',
   'ba75f8917b56511286f684c4a74869f5',
   'c05c9edd4aee99b523ce380e0af10048',
   'c43ea1fccd3f4823dfff869f57890fdc',
   'c5d7153591f244a96ac81655d9e8d012',
   'd349a85d08e93cbc05507abe751f2582',
   'd38efd4457b9823655a575065cddb320',
   'd42835388f571ecda4a00eb3bffa4b03',
   'd6f49f0d6626f8ace875377d1aca70a4',
   'd7e0c48d7ad1e819431aa6cf955ee1d3',
   'd91695c66b329911594065aa834e4019',
   'de2d0e12c474907ef67271c73d3d0a7e',
   'e7f719dd3615e42a26c2496ca8b3401b',
   'e8861f6dc00fa89ad1ee0307d5653073',
   'f7462e1784dee5fec9aa3d91eff3c5a4',
   'f8435247965bed14eb11167e1407b2ef',
   'fbf73ada18f4166851084f259b33bbb7',
   'fce4770ef1a76c846a44203c5fac7bdf'}}}

In [77]:
joblib.dump(EXTRACTED_TRIPLES_NODES_IDS, SAVE_TRIPLES_NODES_IDS_PATH)

['../../../../pai2_knowledge_graphs/2wiki/qwen257b_080226_v2prompts/partial_triples_nodes_ids.joblib']

In [78]:
joblib.dump(MATCHED_TNIDS_TO_QUESTIONS, SAVE_MATCHED_TNIDS_TO_QUESTIONS_PATH)

['../../../../pai2_knowledge_graphs/2wiki/qwen257b_080226_v2prompts/matched_tnids_to_questions.joblib']